version: '3.8'

services:
  ml-dev:
    build:
      context: .
      args:
      - uid=1001
      - gid=1001
      - username=mluser
      - project_name=mlexpenv
    container_name: ml-dev
    image: ml-dev-image
    shm_size: '24gb'
    tty: true
    volumes: 
      - $PWD:/home/mluser/mlexpenv
    command: '/bin/bash'
    ports:
      - 18081-18090:18081-18090
    #runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]