[tool.poetry]
name = "ml-exp-env"
version = "0.1.0"
description = ""
authors = ["k-washi <kai.washizaki@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
hydra-core = ">=1.2.0"
tensorboard = ">=2.8.0"
transformers = ">=4.15.0"
tqdm = ">=4.62.3"
python-dotenv = ">=0.19.2"
matplotlib = ">=1.5"
japanize-matplotlib = ">=1.1.3"
pandas = ">=1.4.1"
joblib = ">=1.1.0"
numpy = ">=1.22.2"
scipy = ">=1.8.0"
seaborn = ">=0.11.2"
pytorch-lightning = ">=1.5.10"
torch = "^1.13.0"
torchaudio = "^0.13.0"
ipywidgets = "^8.0.2"
ffmpeg-python = "0.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
tox = ">=3.24.5"
black = ">=22.1.0"
isort = ">=5.10.1"
mypy = ">=0.941"
flake8 = ">=4.0.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.17.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
